server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false  # Désactive Config Server
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Routes de test
        - id: test-service
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/api/test/**
          filters:
            - StripPrefix=2
        - id: httpbin
          uri: https://httpbin.org
          predicates:
            - Path=/api/httpbin/**
          filters:
            - StripPrefix=2
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
