
# server:
#   port: 8081

# spring:
#   application:
#     name: chat-service
#   datasource:
#     url: jdbc:h2:mem:chatdb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password: ""
#     hikari:
#       maximum-pool-size: 10
#       minimum-idle: 5
#       connection-timeout: 20000
#   jpa:
#     hibernate:
#       ddl-auto: create-drop
#     show-sql: false
#     database-platform: org.hibernate.dialect.H2Dialect
#   h2:
#     console:
#       enabled: false

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#     register-with-eureka: true
#     fetch-registry: true
#   instance:
#     prefer-ip-address: true
#     lease-renewal-interval-in-seconds: 30

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info,metrics
#   endpoint:
#     health:
#       show-details: when-authorized

# # Configuration spécifique au chat
# chat:
#   message:
#     max-length: 1000
#     history-limit: 100
#   room:
#     max-users: 50
#     default-name: "General"
#     max-rooms-per-user: 10
#   file:
#     upload:
#       enabled: true
#       max-size: 10MB
#       allowed-types: jpg,jpeg,png,gif,pdf,txt

# # Configuration OpenFeign pour communiquer avec User Service
# feign:
#   client:
#     config:
#       user-service:
#         connectTimeout: 5000
#         readTimeout: 5000
server:
  port: 8081

spring:
  application:
    name: chat-service
  
  # Configuration JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  # Configuration MySQL
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/chatdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:motdepasse123*}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  # Configuration des transactions
  transaction:
    default-timeout: 30
    rollback-on-commit-failure: true

# Configuration Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health

# Configuration Feign
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic
      user-service:
        connect-timeout: 3000
        read-timeout: 5000

# Configuration Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true
    db:
      enabled: true

# Configuration spécifique au chat
chat:
  room:
    max-participants: 100
    max-message-length: 2000
    recent-messages-limit: 50
  message:
    retention-days: 365
    pagination:
      default-size: 20
      max-size: 100
  websocket:
    enabled: true
    endpoint: /chat-websocket

# Configuration des logs
logging:
  level:
    net.chat.chatservice: INFO
    org.springframework.cloud.openfeign: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-40.40logger{39} : %m%n%wEx"
