# Configuration développement WebSocket Service
server:
  port: 8083

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:websocketdb-dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# Configuration WebSocket développement
websocket:
  endpoint: /ws
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:4200"
    - "http://localhost:5173"
    - "http://localhost:8080"
    - "http://localhost:8081"
    - "http://localhost:8082"
  message-buffer-size: 51200
  send-time-limit: 10000
  send-buffer-size-limit: 512000
  session:
    max-concurrent-sessions: 1000
    max-message-size: 65536
    max-buffer-size: 524288

# JWT moins strict en développement
jwt:
  secret: devSecretKey2024ForWebSocketDevelopment
  expiration: 3600000  # 1 heure en dev pour faciliter les tests

# Configuration WebSocket moins stricte en dev
websocket-config:
  heartbeat-interval: 30000  # 30 secondes en dev
  connection-timeout: 300000  # 5 minutes en dev
  max-connections-per-user: 5  # Plus permissif en dev

# Logging détaillé pour le développement
logging:
  level:
    net.chat.websocket: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.messaging.simp: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# CORS plus permissif en dev
security:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:4200"
      - "http://localhost:5173"
      - "http://localhost:8080"
      - "http://localhost:8081"
      - "http://localhost:8082"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# Désactivation partielle de la sécurité pour les tests
security:
  basic:
    enabled: false

# Configuration services externes moins stricte en dev
service:
  user:
    timeout: 10000  # 10 secondes en dev
  chat:
    timeout: 10000  # 10 secondes en dev

# Résilience moins stricte en dev
resilience:
  circuit-breaker:
    user-service:
      failure-rate-threshold: 70  # Plus permissif en dev
      wait-duration-in-open-state: 5s  # Plus court en dev
    chat-service:
      failure-rate-threshold: 70
      wait-duration-in-open-state: 5s
  retry:
    max-attempts: 2  # Moins de tentatives en dev

# Email désactivé en dev
mail:
  enabled: false

# Configuration pour debugging
debug: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# Fallback configuration si Config Server indisponible
spring:
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 3
        max-interval: 2000
