# Configuration développement WebSocket Service
server:
  port: 8083

# Configuration WebSocket développement
websocket:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:4200"
    - "http://localhost:5173"
    - "http://localhost:8080"
    - "http://localhost:8081"
    - "http://localhost:8082"
  message-buffer-size: 51200
  send-time-limit: 10000
  send-buffer-size-limit: 512000

# Logging détaillé pour le développement
logging:
  level:
    net.chat.websocket: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.messaging.simp: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configuration pour le débogage
debug: true

# Désactivation partielle de la sécurité pour les tests
security:
  basic:
    enabled: false

# Configuration des limites pour le développement
websocket:
  session:
    max-concurrent-sessions: 1000
    max-message-size: 65536
    max-buffer-size: 524288

# Fallback configuration si Config Server indisponible
spring:
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 3
        max-interval: 2000
